//student report card
#include<iostream.h>
#include<conio.h>
#include<stdio.h>
struct data
{char name[20];
int eng,maths;
float percent;
}d;
void main()
{clrscr();
cout<<"ENTER DATA";
cout<<"\nenter name";
gets(d.name);
cout<<"enter marks of english";
cin>>d.eng;
cout<<"enter marks of maths";
cin>>d.maths;
cout<<"enter percent";
cin>>d.percent;
cout<<"\n    DATA";
cout<<"\nNAME" ;
cout<<d.name;
cout<<"\n other detail";
cout<<"\nmarks english"<<d.eng;
cout<<"\nmarks maths"<<d.maths;
cout<<"\npercent"<<d.percent;
getch();
}
/*
ENTER DATA
enter name  Abhishek
enter marks of english 65
enter marks of maths 63
enter percent 64

    DATA
NAME  Abhishek
 other detail
marks English 65
marks maths 63
percent 64 */

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
